### ISSUE TITLE
DAO v0.2

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#136]
- [x] #134 
- [x] Deploy staking program subgraph
- [x] #138
- [x] #140
- [x] #139
- [x] #135 
- [x] #142
- [x] #144
- [x] #143
- [ ] Create a production DAO v0.2 Snapshot page with relevant strategies
- [ ] Announce cut-off `block`, so that the community has time to perform some on-chain transactions to update their `unclaimedRewards` in the staking program.

**Comment by nionis** [comment]
lets add `definition of done`

**Comment by QYuQianchen** [comment]
The other two items are more for the commercial team. Those two tickets are created in notion.
