### ISSUE TITLE
Deploy subgraph for `valencia` release (`monte_rosa` environment)

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#181]
- [x] Deploy channels-only subgraph for valencia release.
- [x] Include NR events into the subgraph
- [x] Deploy new channel subgraph for the monte_rosa environment.
