### ISSUE TITLE
[Bounty] Create Subgraph that indexes HoprChannel

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#22]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction
[The HOPR protocol](https://hoprnet.org/) provides network-level and metadata privacy for every kind of data exchange. A mixnet protects the identity of both sender and recipe ent by routing data via multiple intermediate relay hops that mix traffic.

Payments are handled via probabilistic micropayments, our custom layer-2 scaling solution on top of the Ethereum blockchain.

# Task Description
We need to index HoprChannels using subgraphs from [TheGraph](https://thegraph.com/docs/introduction). The [GraphQL schema](https://github.com/hoprnet/hopr-analytics/blob/main/subgraph-channels/schema.graphql) has been defined in the [folder](https://github.com/hoprnet/hopr-analytics/tree/main/subgraph-channels). Please complete the mapping logic and deploy the subgraph. 

# Definition of complete 
- [ ] Complete [`mapping.ts`](https://github.com/hoprnet/hopr-analytics/blob/main/subgraph-channels/src/mapping.ts) to index HoprChannels' activities: [announce](https://github.com/hoprnet/hoprnet/blob/828e5b3935ff6da74dd512cc0972d4a31339af29/packages/ethereum/contracts/HoprChannels.sol#L70) and [channel update](https://github.com/hoprnet/hoprnet/blob/828e5b3935ff6da74dd512cc0972d4a31339af29/packages/ethereum/contracts/HoprChannels.sol#L75).
- [ ] Modify [`subgraph.yaml`](https://github.com/hoprnet/hopr-analytics/blob/main/subgraph-channels/subgraph.yaml) so that HoprChannels on Goerli network and xDai network are indexed.
   - [ ] Goerli: [0x1b7714DC1D40ef37F612967Bed94a6dF84a93b85](https://goerli.etherscan.io/address/0x1b7714DC1D40ef37F612967Bed94a6dF84a93b85#code) deployed at block 4260231.
   - [ ] xDai: [0x202FAFCF98f694831200Ca3CCa143f675B990a9b](https://blockscout.com/xdai/mainnet/address/0x202FAFCF98f694831200Ca3CCa143f675B990a9b/transactions) deployed at block 15877153.
- [ ] Deploy the subgraph to two Ethereum networks.
- [ ] Create a PR to the `hopr-analytics/subgraph-channels` folder.

# Useful sources
- [HoprChannels smart contract](https://github.com/hoprnet/hoprnet/blob/828e5b3935ff6da74dd512cc0972d4a31339af29/packages/ethereum/contracts/HoprChannels.sol)
- [Deploying the subgraph to multiple Ethereum networks](https://thegraph.com/docs/deploy-a-subgraph#deploying-the-subgraph-to-multiple-ethereum-networks)
- Logics in our in-house indexer: [Annouce](https://github.com/hoprnet/hoprnet/blob/828e5b3935ff6da74dd512cc0972d4a31339af29/packages/core-ethereum/src/indexer/index.ts#L246) and [channel update](https://github.com/hoprnet/hoprnet/blob/828e5b3935ff6da74dd512cc0972d4a31339af29/packages/core-ethereum/src/indexer/index.ts#L270)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 HOPR (95.35 USD @ $0.48/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,039,340.58 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [controlcpluscontrolv](https://gitcoin.co/controlcpluscontrolv) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?mutate_worker_action=approve&worker=controlcpluscontrolv) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?mutate_worker_action=reject&worker=controlcpluscontrolv))_.**

The work is fairly straightforward from what you laid out and would love to do it! I do a lot with data analytics so this is in my area of expertise. Let me know if you have questions!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741).

**Comment by ManyRios** [comment]
Working

**Comment by gitcoinbot** [comment]
@manyrios Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by ManyRios** [comment]
Yes @gitcoinbot

**Comment by ManyRios** [comment]
.

**Comment by gitcoinbot** [comment]
@manyrios Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by ManyRios** [comment]
Yep

**Comment by QYuQianchen** [comment]
Hi @ManyRios. Could you please create a WIP PR with your current code base to the repo?

**Comment by ManyRios** [comment]
Hi, ok I will

**Comment by QYuQianchen** [comment]
Hi @ManyRios I don't think i've received it. Could you please communicate in this thread?

**Comment by gitcoinbot** [comment]
@manyrios Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by ManyRios** [comment]
I'll make the PR today, sorry for the delay

**Comment by ManyRios** [comment]
almost ready to deploy

**Comment by ManyRios** [comment]
I sent a email to  tech@hoprnet.org

**Comment by ManyRios** [comment]
Waiting :)

**Comment by jjperezaguinaga** [comment]
@ManyRios ah! Sorry about that, will give you an update today :)

**Comment by nionis** [comment]
posting here the issue @ManyRios has:

```
graph codegen

  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2

  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3

  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4

  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2

√ Apply migrations

× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

 

  Path: dataSources > 0 > eventHandlers > 0

  Event with signature 'Announcement(address indexed account,bytes multiaddr)' not present in ABI 'HoprChannels'.

  Available events:

  - Announcement(indexed address,bytes)

  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))

 

  Path: dataSources > 0 > eventHandlers > 1

  Event with signature 'ChannelUpdate(address indexed partyA,address indexed partyB,Channel newState)' not present in ABI 'HoprChannels'.

  Available events:

  - Announcement(indexed address,bytes)

  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ManyRios** [comment]
> posting here the issue @ManyRios has:
> 
> ```
> graph codegen
> 
>   Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
> 
>   Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
> 
>   Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
> 
>   Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
> 
> √ Apply migrations
> 
> × Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:
> 
>  
> 
>   Path: dataSources > 0 > eventHandlers > 0
> 
>   Event with signature 'Announcement(address indexed account,bytes multiaddr)' not present in ABI 'HoprChannels'.
> 
>   Available events:
> 
>   - Announcement(indexed address,bytes)
> 
>   - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
> 
>  
> 
>   Path: dataSources > 0 > eventHandlers > 1
> 
>   Event with signature 'ChannelUpdate(address indexed partyA,address indexed partyB,Channel newState)' not present in ABI 'HoprChannels'.
> 
>   Available events:
> 
>   - Announcement(indexed address,bytes)
> 
>   - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
> 
> error Command failed with exit code 1.
> 
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

That's right

**Comment by jjperezaguinaga** [comment]
Following up here on some comments from @nionis

> The issue is not with the ABI but with the subgraph.yaml file, it looks like the events we specified don't match the ones in the ABI, the quickest thing I would try is to copy paste the Available events into subgraph.yaml

these ones seem to be `Annoucement` and `ChannelUpdate`. Can you give that a try? Furthermore, it would be great to have a PR attached to this issue so we can replicate this error locally and see how we can help :)

**Comment by ManyRios** [comment]
Ok, I will

**Comment by jjperezaguinaga** [comment]
@ManyRios Let us know if you have an update here, would be great to have a PR or something we can take a look and support as needed ☺️

**Comment by ManyRios** [comment]
`graph codegen
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
√ Apply migrations
× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > eventHandlers > 0
  Event with signature 'Announcement(indexed address, bytes)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ManyRios** [comment]
> graph codegen
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
√ Apply migrations
× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > eventHandlers > 0
  Event with signature 'Announcement(indexed address, bytes)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Following up here on some comments from @nionis
> 
> > The issue is not with the ABI but with the subgraph.yaml file, it looks like the events we specified don't match the ones in the ABI, the quickest thing I would try is to copy paste the Available events into subgraph.yaml
> 
> these ones seem to be `Annoucement` and `ChannelUpdate`. Can you give that a try? Furthermore, it would be great to have a PR attached to this issue so we can replicate this error locally and see how we can help :)

graph codegen
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
√ Apply migrations
× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > eventHandlers > 0
  Event with signature 'Announcement(indexed address, bytes)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ManyRios** [comment]
> Following up here on some comments from @nionis
> 
> > The issue is not with the ABI but with the subgraph.yaml file, it looks like the events we specified don't match the ones in the ABI, the quickest thing I would try is to copy paste the Available events into subgraph.yaml
> 
> these ones seem to be `Annoucement` and `ChannelUpdate`. Can you give that a try? Furthermore, it would be great to have a PR attached to this issue so we can replicate this error locally and see how we can help :)

here is the the output:

graph codegen
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
√ Apply migrations
× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > eventHandlers > 0
  Event with signature 'Announcement(indexed address, bytes)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jjperezaguinaga** [comment]
Hi @ManyRios ! Can you push your work on your own branch so we can have a PR and see these changes? We want to support you here, but copy and pasting error code is not the best way on how to do so. By pushing your branch we can replicate the same error you are having, thanks!

**Comment by gitcoinbot** [comment]
@manyrios Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by ManyRios** [comment]
I'm not able to make push neither.... take a look on the actually subgraph.yaml(not modied) and running yarn codegen. This is the error: 

yarn run v1.22.5
$ graph codegen
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
√ Apply migrations
× Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 0 > eventHandlers > 0
  Event with signature 'Announcement(address indexed account,bytes multiaddr)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))

  Path: dataSources > 0 > eventHandlers > 1
  Event with signature 'ChannelUpdate(address indexed partyA,address indexed partyB,Channel newState)' not present in ABI 'HoprChannels'.
  Available events:
  - Announcement(indexed address,bytes)
  - ChannelUpdate(indexed address,indexed address,(uint256,uint256,bytes32,bytes32,uint256,uint256,uint256,uint256,uint8,uint256,uint32,bool))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ManyRios** [comment]
https://github.com/hoprnet/hopr-analytics/pull/40

**Comment by gitcoinbot** [comment]
@manyrios Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@manyrios due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/22/100025741?snooze=100)

**Comment by jjperezaguinaga** [comment]
The team solved this one internally, @gitcoinbot feel free to cancel the bounty cc @QYuQianchen
