### ISSUE TITLE
[Bounty] Token provenance and destination of Genesis DAO over time

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#33]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction
Previously a detailed analysis on the ["position of HOPR DAO members"](https://github.com/hoprnet/hopr-analytics/issues/2) was carried out. We'd like to continue this analysis and look into the position of HOPR Genesis DAO over time.

# Task Description

HOPR (Ethereum mainnet), xHOPR (xDAI chain), wxHOPR (xDAI chain) are in the scope of this analysis and are refered altogether as "tokens".
To understand the position of Genesis DAO over time, the following aspects should be included
- Provenance of tokens over time
- Destination of tokens over time 
Provenance and destination can be (not exhaustive): "presale", "honeyswap", "avado_airdrop", "distributor", "uniswap_liquidity_provider", "uniswap'. 

# Definition of complete

- [ ] A working DuneAnalytics/FlipsideCrypto dashboard that contains all the required. 
- [ ] A table of all the Genesis DAO addresses
- [ ] With an address given as a parameter (see ["use parameters in DuneAnalytics"](https://docs.duneanalytics.com/about/tutorials/tips#filter-queries-and-dashboards-with-parameters)), plot a chart that shows the following values over time (x-axis is "date"):
   - [ ] a stacked bar chart on the incoming tokens grouped by source.
   - [ ] a stacked bar chart on the outgoing tokens grouped by destination.
   - [ ] a line chart on the token balance.
This sketch shows how the said chart looks like
![image](https://user-images.githubusercontent.com/10935300/121516106-22e89780-c9ee-11eb-95bd-7ea62dffddac.png)
- [ ] A aggregated chart that is similar to the above-mentioned one, but for all the Genesis DAO addresses.
- [ ] A PR to the [`hoprnet/hopr-analytics` repo](https://github.com/hoprnet/hopr-analytics) according to [this template](https://raw.githubusercontent.com/hoprnet/hopr-analytics/main/.github/PULL_REQUEST_TEMPLATE/query.md). Note that queries should be well-documented.

# Useful sources

- [Position of Genesis DAO](https://duneanalytics.com/t0b/DAO-Members)
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 HOPR (86.77 USD @ $0.29/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/33/100025856).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/33/100025856).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,014,383.94 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [dedesupri93](https://gitcoin.co/dedesupri93) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/33/100025856?mutate_worker_action=approve&worker=dedesupri93) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/33/100025856?mutate_worker_action=reject&worker=dedesupri93))_.**

I want to exited inthis room, what i do?

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/33/100025856).

**Comment by sriram-vasudevan** [comment]
When will contributors be intimated if they are accepted?
