### ISSUE TITLE
Behavior on rewards from HOPR liquidity mining program ("HOPR Farm")

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#4]
_The following is a bounty issue, meant for external contributors to pick up and work on the analytics of HOPR tokens._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Followed by the token launch, a 13-week liquidity mining program, "HOPR Farm", started at the end of March 2021. HOPR Farm [incentivizes token holders to provide liquidity](https://medium.com/hoprnet/a-simple-guide-to-the-hopr-farm-5m-hopr-rewards-4e6d4e931570) for HOPR-DAI pair on Uniswap V2. The total reward amounts to 5 million HOPR tokens. We have provided a breakdown of its associated transaction costs and the schedule of farm rewarding time [in a blog post](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae). 

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the 30-million LBP sale part of HOPR token launch ([See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale)) and 5-million HOPR liquidity mining program - HOPR Farm ([See the dashboard here](https://duneanalytics.com/qyuqianchen/Farm)).

# Task Description

HOPR's liquidity mining program "HOPR Farm" has started since the end of March 2021, where 5 million HOPR tokens will be equally distributed into 13 "seasons" to incentivize liquidity providers ("farmers") of HOPR-DAI pair on Uniswap V2. At the end of each "season" (also referred as "period" [in the smart contract](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f#readContract)) rewards will be allocated according to the eligible amount of HOPR-DAI liquidity provider tokens (UNI-V2 tokens, also referred as "seeds"), which is the amount UNI-V2 tokens being staked ("planted") into the "HoprFarm" contract throughout the entire season. A detailed explanation can be found [in this blog](https://medium.com/hoprnet/a-simple-guide-to-the-hopr-farm-5m-hopr-rewards-4e6d4e931570).

We'd learn more about the farmers' behavior in the liquidity mining program. Notably, on the "harvesting" of rewards: 
1. How many farmers have claimed ("harvested") their liquidity mining rewards? What is the amount?
2. How many rewards remain in each farmer's wallet?
3. How many rewards were swapped in the HOPR-DAI liquidity pool?
4. How many rewards were later compounded into the Farm? 
5. What other approaches did farmers follow with their earnings? What is the amount for each approach?

# Definition of complete
We expect to see a DuneAnalytics dashboard (or a working Nodejs project or python project) that contains visualizations/queries which provide answers (both table and chart) to all the questions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.

- [ ] A table and a bar chart that plots the amount of tokens farmers harvested from HOPR farm over time.
- [ ] A table that shows the addresses of farmers who keep their earnings in their wallets, together with their corresponding earnings. 
- [ ] A table and a bar chart that plots the amount of earnings farmers dumped into HOPR-DAI liquidity pool over time. Please include transaction hash in the table.
- [ ] A table and a bar chart that shows the amount of earnings farmers compounded into HOPR Farm over time. Please include `season` or `period` in the table.
- [ ] A table that lists out all the other options that farmers did with their earnings and the corresponding amount. 
- [ ] Finally a pie chart that gives the overview of harvested rewards grouped by different usages.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- [Analytics dashboards]
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 HOPR (215.38 USD @ $0.72/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,146,961.19 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 7 months from now.
Please review their action plans below:


**1) [baldator](https://gitcoin.co/baldator) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?mutate_worker_action=approve&worker=baldator) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?mutate_worker_action=reject&worker=baldator))_.**

I'd love to help you with this bounty. 
I'll provide a DuneAnalytics dashboard with the requested information.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552).

**Comment by bobu4** [comment]
![image](https://user-images.githubusercontent.com/48527047/116258782-eb939380-a77d-11eb-9656-fc95be7374b4.png)

**Comment by bobu4** [comment]
![image](https://user-images.githubusercontent.com/48527047/116435472-0f290d80-a854-11eb-96e8-9df5b0c1b1b5.png)

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by bobu4** [comment]
I'm still on.

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by bobu4** [comment]
Still on.

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by bobu4** [comment]
On

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by bobu4** [comment]
On

**Comment by QYuQianchen** [comment]
Hi @bobu4! Please create a WIP PR to the `main` branch of `hopr-analtyics` repo, with the following steps:
1. Fork `hopr-analytics` repo to your local machine.
2. Create a branch `farm-rewards-behavior`.
3. On the said branch, create a subfolder `farm-rewards-behavior`and add your source code there. 
4. Commit your code and push to remote.
5. Create a WIP PR with https://github.com/hoprnet/hopr-analytics/compare/main...farm-rewards-behavior?template=standalone-app.md

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by gitcoinbot** [comment]
@bobu4 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@bobu4 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@bobu4 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/4/100025552?snooze=100)

**Comment by QYuQianchen** [comment]
Hi @bobu4 Please create a WIP PR as described before until 18 June. Without a WIP PR, we would unfortunately assign this task to other community member. Thank you for your understanding :)

> Hi @bobu4! Please create a WIP PR to the `main` branch of `hopr-analtyics` repo, with the following steps:
> 
> 1. Fork `hopr-analytics` repo to your local machine.
> 2. Create a branch `farm-rewards-behavior`.
> 3. On the said branch, create a subfolder `farm-rewards-behavior`and add your source code there.
> 4. Commit your code and push to remote.
> 5. Create a WIP PR with https://github.com/hoprnet/hopr-analytics/compare/main...farm-rewards-behavior?template=standalone-app.md

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 300.0 HOPR  (51.9 USD @ $0.17/HOPR) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,405,045.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
