### ISSUE TITLE
[Bounty] Improve HODL analysis

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-community#43]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Task Description
Complete and improve analysis based on[ code in the repo](https://github.com/hoprnet/hopr-community/tree/main/queries/HOPR%20HODL%20List).

# Definition of complete
- A working python project or with another data analytics platform (e.g. DuneAnalytics/BigQuery) that contains scripts/queries that describes HOPR's HODLer positions.
- Instruction on installation and running should be well-documented.

# Useful sources

- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1.0 HOPR (0.25 USD @ $0.25/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,872,622.76 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 4 months from now.
Please review their action plans below:


**1) [damiscosilas](https://gitcoin.co/damiscosilas) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?mutate_worker_action=approve&worker=damiscosilas) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?mutate_worker_action=reject&worker=damiscosilas))_.**

I would love to be working with you to improve your association

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091).

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-community/43/100026091?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 1.0 HOPR  (0.17 USD @ $0.17/HOPR) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,404,457.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
