### ISSUE TITLE
Matic Testnet v1

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-community#94]
# Introduction

We are launching a HOPR testnet in the Polygon mainnet network for testing the reliability of our network using a more congested network (in contrast to xDAI). To increase the familiarity and adoption of HOPR nodes, we'll also reward participants of this testnet with some staking NFTs they can use in our [Staking Program](https://stake.hoprnet.org/).

![image](https://user-images.githubusercontent.com/1128312/128518925-a75f67e4-b368-42f8-8025-55cc93ebb5b3.png)

# Tasks running testnet

## HOPRd (requirements)
- [x] hoprnet/hoprnet#2183
- [x] hoprnet/hoprnet#2126
- [x] hoprnet/hoprnet#2266
- [x] hoprnet/hoprnet#2267
- [x] hoprnet/hoprnet#2268
- [x] hoprnet/hoprnet#2269
- [x] hoprnet/hoprnet#2273

## HOPRd (known bugs)
- [x] hoprnet/hoprnet#2270

## Documentation
- [x] #110
- [x] #103
- [x] #111
- [x] #112
- [x] #113

## HOPR Channels Subgraph
- [x] hoprnet/hopr-devrel#6

## Dashboard
- [x] #95
- [x] hoprnet/hopr-leaderboard#56
- [x] hoprnet/hopr-leaderboard#57
- [x] hoprnet/hopr-leaderboard#58
- [x] hoprnet/hopr-leaderboard#59
- [x] hoprnet/hopr-leaderboard#60
- [x] hoprnet/hopr-leaderboard#61
- [x] hoprnet/hopr-leaderboard#62
- [x] hoprnet/hopr-leaderboard#63
- [x] hoprnet/hopr-leaderboard#64

# Post-launch
- [x] #100
- [x] #101
- [x] #102

**Comment by jjperezaguinaga** [comment]
Signing in progress in hoprnet/hoprnet#2226

**Comment by tolbrino** [comment]
I suspect this epic can be concluded. The 2 open tasks have already been assigned to the Rio epic.

**Comment by jjperezaguinaga** [comment]
@tolbrino Indeed, will remove them from here.

**Comment by nionis** [comment]
✅ I accept that this epic was completed
